#+TITLE: things todo

* TODO import each document in the legal.cf.sg _posts and establish backward compatibility [0/9]

2013-12-12-term_sheet_for_convertible_note.html
2013-11-03-convertible_loan_agreement.html
2013-12-01-purchase_agreement_for_convertible_note.html
2013-11-03-resolution_of_transfer_of_shares.html
2013-11-03-share_transfer_instrument.html
2013-11-03-shareholders_agreement.html
2013-11-14-consulting_agreement.html

create Google Spreadsheets API interface to read cap table

create Google Spreadsheets API interface to read key/value config

user-facing documentation to edit cap tables


import each document in the Y Combinator Series AA series

import each document in the Y Combinator SAFE series

read the SAFE primer

import each document in the Techstars model docs series

import JFDI's Founder Agreement

import JFDI's


** what are the essentials?

- parties. infer jurisdiction from company location.
- amount.
- valuation. (enter the cap table.)
- discount
- type of security

** View the drafts

- visualization of the terms and implications for each party
- easily try a different security type

** display range of possibilities

- help to filter the range based on which are acceptable to investors.

* TODO define web app user model

different users should be able to log in to collaboratively edit the same deal.



